version: '3'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: tic_tac_toe_db
    networks:
      - shared-network
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
